"use client";

import type { InventoryItem, Receipt, Room } from "@stuffhub/domain";
import { ArrowLeft, ImagePlus, X } from "lucide-react";
import { useState } from "react";
import { CurrencyField, DateField } from "./form-fields";

type ItemInput = Pick<InventoryItem, "name" | "category" | "description" | "estimatedReplacementValueCents" | "purchaseYear" | "serialNumber" | "ownerName" | "photoUris">;
type Attachments = { itemPhotoFiles: File[]; receiptPhotoFiles: File[]; existingReceiptIds: string[]; receipt: { merchant: string; purchaseDate: string | null; totalCents: number; imageUri: string | null; description: string; photoUris: string[] } | null; warranty: { provider: string; policyNumber: string; purchaseDate: string | null; durationMonths: number; description: string; claimContact: string } | null };
type Props = { rooms: Room[]; receipts: Receipt[]; room?: Room; item?: InventoryItem; ownerNames?: string[]; onBack: () => void; onAddRoom: (name: string) => string; onSave: (input: ItemInput, roomId: string, attachments: Attachments) => void; onDelete?: () => void };

export function ItemEditor({ rooms, receipts, room, item, ownerNames = [], onBack, onAddRoom, onSave, onDelete }: Props) {
  const [name, setName] = useState(item?.name ?? ""); const [ownerName, setOwnerName] = useState(item?.ownerName ?? ""); const [category, setCategory] = useState(item?.category ?? "Other");
  const [itemPhotos, setItemPhotos] = useState<Array<{ file?: File; uri: string }>>(() => (item?.photoUris ?? []).map((uri) => ({ uri })));
  const [value, setValue] = useState(item ? (item.estimatedReplacementValueCents / 100).toFixed(2) : ""); const [year, setYear] = useState(item?.purchaseYear?.toString() ?? ""); const [serial, setSerial] = useState(item?.serialNumber ?? ""); const [description, setDescription] = useState(item?.description ?? ""); const [roomId, setRoomId] = useState(item?.roomId ?? room?.id ?? "");
  const [showNewRoom, setShowNewRoom] = useState(false); const [newRoomName, setNewRoomName] = useState("");
  const [showReceipt, setShowReceipt] = useState(false); const [merchant, setMerchant] = useState(""); const [receiptDate, setReceiptDate] = useState(""); const [receiptTotal, setReceiptTotal] = useState(""); const [receiptDescription, setReceiptDescription] = useState(""); const [receiptPhotos, setReceiptPhotos] = useState<Array<{ file: File; uri: string }>>([]); const [existingReceiptIds, setExistingReceiptIds] = useState<string[]>([]);
  const [showWarranty, setShowWarranty] = useState(false); const [provider, setProvider] = useState(""); const [policy, setPolicy] = useState(""); const [warrantyDate, setWarrantyDate] = useState(""); const [duration, setDuration] = useState(""); const [warrantyDescription, setWarrantyDescription] = useState(""); const [claimContact, setClaimContact] = useState("");
  const categories = ["Electronics", "Furniture", "Appliances", "Jewelry", "Collectibles", "Tools", "Clothing", "Other"];
  const reusableOwners = Array.from(new Set([...ownerNames, ...rooms.flatMap((entry) => entry.items).map((entry) => entry.ownerName)].filter((owner): owner is string => Boolean(owner)))).sort();
  const choices = (options: Array<{ id: string; label: string }>, selected: string[], toggle: (id: string) => void) => <div className="choice-list compact">{options.map((option) => <button type="button" key={option.id} className={`choice ${selected.includes(option.id) ? "selected" : ""}`} onClick={() => toggle(option.id)}>{option.label}</button>)}</div>;
  const addItemPhotos = (files: FileList | null) => setItemPhotos((current) => [...current, ...Array.from(files ?? []).map((file) => ({ file, uri: URL.createObjectURL(file) }))]);
  const removeNewItemPhoto = (uri: string) => setItemPhotos((current) => { URL.revokeObjectURL(uri); return current.filter((photo) => photo.uri !== uri); });
  const save = () => onSave({ name: name.trim(), ownerName: ownerName?.trim() || null, category, description, estimatedReplacementValueCents: Math.round(Number(value || 0) * 100), purchaseYear: Number(year) >= 1900 ? Number(year) : null, serialNumber: serial.trim() || null, photoUris: itemPhotos.map((photo) => photo.uri) }, roomId, {
    itemPhotoFiles: itemPhotos.flatMap((photo) => photo.file ? [photo.file] : []),
    receiptPhotoFiles: receiptPhotos.map((photo) => photo.file),
    existingReceiptIds,
    receipt: merchant.trim() ? { merchant: merchant.trim(), purchaseDate: receiptDate || null, totalCents: Math.round(Number(receiptTotal || 0) * 100), imageUri: receiptPhotos[0]?.uri ?? null, description: receiptDescription, photoUris: receiptPhotos.map((photo) => photo.uri) } : null,
    warranty: provider.trim() ? { provider: provider.trim(), policyNumber: policy, purchaseDate: warrantyDate || null, durationMonths: Number(duration) || 0, description: warrantyDescription, claimContact } : null,
  });
  const createRoom = () => { if (!newRoomName.trim()) return; setRoomId(onAddRoom(newRoomName.trim())); setNewRoomName(""); setShowNewRoom(false); };

  return <section className="app-page">
    <button className="back-button icon-label" onClick={onBack}><ArrowLeft size={17} /> Back</button><p className="eyebrow">{room?.name ?? "Room"}</p><h1 className="page-title">{item ? "Update this item." : "Document an item."}</h1>
    <div className="form-grid">
      <Field label="Room *" wide><div className="choice-list compact">{rooms.map((entry) => <button type="button" key={entry.id} className={`choice ${roomId === entry.id ? "selected" : ""}`} onClick={() => setRoomId(entry.id)}>{entry.name}</button>)}<button type="button" className="choice" onClick={() => setShowNewRoom((open) => !open)}>{showNewRoom ? "Cancel" : "Add Room +"}</button></div>{showNewRoom ? <div className="inline-room"><input value={newRoomName} onChange={(event) => setNewRoomName(event.target.value)} placeholder="Room name" /><button type="button" className="button ghost" disabled={!newRoomName.trim()} onClick={createRoom}>Add Room</button></div> : null}</Field>
      <Field label="Item name *" wide><input value={name} onChange={(event) => setName(event.target.value)} /></Field>
      <Field label="Item photos" wide><label className="item-photo-picker"><ImagePlus size={21} /><span><strong>Add photos</strong><small>Choose one or more clear views of the item</small></span><input hidden type="file" accept="image/*" multiple onChange={(event) => addItemPhotos(event.target.files)} /></label>{itemPhotos.length ? <div className="item-photo-previews">{itemPhotos.map((photo) => <div key={photo.uri}><img src={photo.uri} alt="Item preview" /><button type="button" aria-label="Remove photo" onClick={() => removeNewItemPhoto(photo.uri)}><X size={15} /></button></div>)}</div> : null}</Field>
      <Field label="Owner" wide><input list="item-owner-options" value={ownerName ?? ""} onChange={(event) => setOwnerName(event.target.value)} placeholder="Optional — type or choose a person" /><datalist id="item-owner-options">{reusableOwners.map((owner) => <option key={owner} value={owner} />)}</datalist></Field>
      <Field label="Category" wide>{choices(categories.map((entry) => ({ id: entry, label: entry })), [category], setCategory)}</Field>
      <Field label="Replacement value"><CurrencyField value={value} onChange={setValue} /></Field><Field label="Purchase year"><input inputMode="numeric" maxLength={4} value={year} onChange={(event) => setYear(event.target.value.replace(/\D/g, ""))} /></Field>
      <Field label="Serial number" wide><input value={serial} onChange={(event) => setSerial(event.target.value)} /></Field><Field label="Description" wide><textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></Field>
    </div>
    <div className="inline-add-stack"><button className="button ghost" onClick={() => setShowReceipt((open) => !open)}>{showReceipt ? "Hide receipt" : "Add receipt"}</button><button className="button ghost" onClick={() => setShowWarranty((open) => !open)}>{showWarranty ? "Hide warranty" : "Add warranty"}</button></div>
    {showReceipt ? <section className="inline-record"><h2>Receipt details</h2><div className="form-grid"><Field label="Merchant"><input value={merchant} onChange={(event) => setMerchant(event.target.value)} /></Field><Field label="Purchase date"><DateField value={receiptDate} onChange={setReceiptDate} /></Field><Field label="Total"><CurrencyField value={receiptTotal} onChange={setReceiptTotal} /></Field><Field label="Photos" wide><input type="file" accept="image/*" multiple onChange={(event) => setReceiptPhotos(Array.from(event.target.files ?? []).map((file) => ({ file, uri: URL.createObjectURL(file) })))} /></Field><Field label="Details" wide><textarea rows={3} value={receiptDescription} onChange={(event) => setReceiptDescription(event.target.value)} /></Field><Field label="Or attach an existing receipt" wide>{choices(receipts.map((receipt) => ({ id: receipt.id, label: receipt.merchant })), existingReceiptIds, (id) => setExistingReceiptIds((current) => current.includes(id) ? current.filter((entry) => entry !== id) : [...current, id]))}</Field></div></section> : null}
    {showWarranty ? <section className="inline-record"><h2>Warranty details</h2><div className="form-grid"><Field label="Provider"><input value={provider} onChange={(event) => setProvider(event.target.value)} /></Field><Field label="Policy / contract"><input value={policy} onChange={(event) => setPolicy(event.target.value)} /></Field><Field label="Purchase date"><DateField value={warrantyDate} onChange={setWarrantyDate} /></Field><Field label="Duration in months"><input inputMode="numeric" value={duration} onChange={(event) => setDuration(event.target.value.replace(/\D/g, ""))} /></Field><Field label="Claim contact" wide><input value={claimContact} onChange={(event) => setClaimContact(event.target.value)} /></Field><Field label="Description" wide><textarea rows={3} value={warrantyDescription} onChange={(event) => setWarrantyDescription(event.target.value)} /></Field></div></section> : null}
    <div className="form-actions"><button className="button primary" disabled={!name.trim() || !roomId} onClick={save}>Save {item ? "changes" : "item"}</button>{onDelete ? <button className="button danger" onClick={onDelete}>Delete item</button> : null}</div>
  </section>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`form-field ${wide ? "wide" : ""}`}><span>{label}</span>{children}</label>; }
