"use client";
import { useState } from "react";
import type { InventoryItem, MaintenanceReminder, Receipt, Room, Warranty } from "@stuffhub/domain";
import { CurrencyField, DateField } from "./form-fields";

type ItemInput = Pick<InventoryItem, "name" | "category" | "description" | "estimatedReplacementValueCents" | "purchaseYear" | "serialNumber"> & { modelNumber?: string | null; photoUris?: string[] };
export type RichReceiptInput = Pick<Receipt, "merchant" | "purchaseDate" | "totalCents" | "imageUri"> & { description?: string; photoUris?: string[]; itemIds?: string[] };

export function RecordForm({ kind, rooms, receipts, warranty, onBack, onSaveAppliance, onSaveWarranty, onSaveMaintenance }: { kind: "appliance" | "warranty" | "maintenance"; rooms: Room[]; receipts: Receipt[]; warranty?: Warranty; onBack: () => void; onSaveAppliance: (roomId: string, item: ItemInput) => void; onSaveWarranty: (warranty: Omit<Warranty, "id">) => void; onSaveMaintenance: (reminder: Omit<MaintenanceReminder, "id">) => void }) {
  const items = rooms.flatMap((room) => room.items); const [title, setTitle] = useState(warranty?.provider ?? ""); const [description, setDescription] = useState(warranty?.description ?? ""); const [date, setDate] = useState(warranty?.purchaseDate ?? ""); const [roomId, setRoomId] = useState(rooms[0]?.id ?? ""); const [itemIds, setItemIds] = useState<string[]>(warranty?.itemIds ?? []); const [photos, setPhotos] = useState<string[]>(warranty?.documentUris ?? []); const [model, setModel] = useState(""); const [serial, setSerial] = useState(""); const [provider, setProvider] = useState(warranty?.provider ?? ""); const [policy, setPolicy] = useState(warranty?.policyNumber ?? ""); const [duration, setDuration] = useState(warranty?.durationMonths.toString() ?? ""); const [claimContact, setClaimContact] = useState(warranty?.claimContact ?? ""); const [receiptId, setReceiptId] = useState<string | null>(warranty?.receiptId ?? null); const [frequency, setFrequency] = useState<MaintenanceReminder["frequency"]>("annual");
  const toggle = (value: string) => setItemIds((current) => current.includes(value) ? current.filter((id) => id !== value) : [...current, value]);
  const save = () => { if (!title.trim()) return; if (kind === "appliance") onSaveAppliance(roomId, { name: title.trim(), category: "Appliances", description, estimatedReplacementValueCents: 0, purchaseYear: null, serialNumber: serial.trim() || null, modelNumber: model.trim() || null, photoUris: photos }); if (kind === "warranty") onSaveWarranty({ provider: provider.trim() || title.trim(), policyNumber: policy, purchaseDate: date || null, durationMonths: Number(duration) || 0, description, claimContact, itemIds, receiptId, documentUris: photos }); if (kind === "maintenance") onSaveMaintenance({ title: title.trim(), description, startDate: date, frequency, itemIds }); };
  return <section className="app-page"><button className="back-button" onClick={onBack}>‹ Back</button><p className="eyebrow">My home</p><h1 className="page-title">{kind === "appliance" ? "Add an appliance." : kind === "warranty" ? warranty ? "Edit warranty." : "Add a warranty." : "Schedule maintenance."}</h1><div className="form-grid"><Field label={`${kind} name *`} wide><input value={title} onChange={(e) => setTitle(e.target.value)} /></Field>{kind === "appliance" ? <><Field label="Room" wide><Choices options={rooms.map((x) => ({ id: x.id, label: x.name }))} selected={[roomId]} onClick={setRoomId} /></Field><Field label="Model number"><input value={model} onChange={(e) => setModel(e.target.value)} /></Field><Field label="Serial number"><input value={serial} onChange={(e) => setSerial(e.target.value)} /></Field></> : null}{kind === "warranty" ? <><Field label="Provider"><input value={provider} onChange={(e) => setProvider(e.target.value)} /></Field><Field label="Policy / contract number"><input value={policy} onChange={(e) => setPolicy(e.target.value)} /></Field><Field label="Purchase date"><DateField value={date} onChange={setDate} /></Field><Field label="Duration in months"><input inputMode="numeric" value={duration} onChange={(e) => setDuration(e.target.value.replace(/\D/g, ""))} /></Field><Field label="Claim contact or website" wide><input value={claimContact} onChange={(e) => setClaimContact(e.target.value)} /></Field><Field label="Attach receipt" wide><Choices options={receipts.map((x) => ({ id: x.id, label: x.merchant }))} selected={receiptId ? [receiptId] : []} onClick={(id) => setReceiptId(receiptId === id ? null : id)} /></Field></> : null}{kind === "maintenance" ? <><Field label="Start date"><DateField value={date} onChange={setDate} /></Field><Field label="Frequency" wide><Choices options={[{ id: "one_time", label: "One time" }, { id: "monthly", label: "Monthly" }, { id: "quarterly", label: "Quarterly" }, { id: "semiannual", label: "Every 6 months" }, { id: "annual", label: "Annual" }]} selected={[frequency]} onClick={(id) => setFrequency(id as MaintenanceReminder["frequency"])} /></Field></> : null}{kind !== "appliance" ? <Field label="Attach items or appliances" wide><Choices options={items.map((x) => ({ id: x.id, label: x.name }))} selected={itemIds} onClick={toggle} /></Field> : null}<Field label="Description / claim notes" wide><textarea rows={4} value={description} onChange={(e) => setDescription(e.target.value)} /></Field>{kind !== "maintenance" ? <Field label="Photos or documents" wide><input type="file" accept="image/*" multiple onChange={(e) => setPhotos(Array.from(e.target.files ?? []).map((file) => URL.createObjectURL(file)))} /></Field> : null}</div><div className="form-actions"><button className="button primary" disabled={!title.trim()} onClick={save}>{warranty ? "Save changes" : `Save ${kind}`}</button></div></section>;
}

export function StandaloneReceiptForm({ items, onBack, onSave }: { items: InventoryItem[]; onBack: () => void; onSave: (input: RichReceiptInput) => void }) { const [merchant, setMerchant] = useState(""); const [date, setDate] = useState(""); const [total, setTotal] = useState(""); const [description, setDescription] = useState(""); const [itemIds, setItemIds] = useState<string[]>([]); const [photos, setPhotos] = useState<string[]>([]); const toggle = (value: string) => setItemIds((current) => current.includes(value) ? current.filter((id) => id !== value) : [...current, value]); return <section className="app-page"><button className="back-button" onClick={onBack}>‹ Back</button><p className="eyebrow">Proof of purchase</p><h1 className="page-title">Create a receipt.</h1><div className="form-grid"><Field label="Merchant *" wide><input value={merchant} onChange={(e) => setMerchant(e.target.value)} /></Field><Field label="Purchase date"><DateField value={date} onChange={setDate} /></Field><Field label="Receipt total"><CurrencyField value={total} onChange={setTotal} /></Field><Field label="Items on this receipt" wide><Choices options={items.map((x) => ({ id: x.id, label: x.name }))} selected={itemIds} onClick={toggle} /></Field><Field label="Receipt photos" wide><input type="file" accept="image/*" multiple onChange={(e) => setPhotos(Array.from(e.target.files ?? []).map((file) => URL.createObjectURL(file)))} /></Field><Field label="Order, payment, and return details" wide><textarea rows={4} value={description} onChange={(e) => setDescription(e.target.value)} /></Field></div><div className="form-actions"><button className="button primary" disabled={!merchant.trim()} onClick={() => onSave({ merchant: merchant.trim(), purchaseDate: date || null, totalCents: Math.round(Number(total || 0) * 100), imageUri: photos[0] ?? null, photoUris: photos, itemIds, description })}>Save receipt</button></div></section>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`form-field ${wide ? "wide" : ""}`}><span>{label}</span>{children}</label>; }
function Choices({ options, selected, onClick }: { options: Array<{ id: string; label: string }>; selected: string[]; onClick: (id: string) => void }) { return options.length ? <div className="choice-list compact">{options.map((x) => <button type="button" key={x.id} className={`choice ${selected.includes(x.id) ? "selected" : ""}`} onClick={() => onClick(x.id)}>{x.label}</button>)}</div> : <p className="form-note">No records available yet.</p>; }
