FROM kong/kong:3.9.1

USER root
COPY --chown=kong:kong deploy/volumes/api/kong.yml /home/kong/temp.yml
COPY --chown=kong:kong deploy/volumes/api/kong-entrypoint.sh /home/kong/kong-entrypoint.sh
RUN chmod 0555 /home/kong/kong-entrypoint.sh
USER kong

ENTRYPOINT ["/home/kong/kong-entrypoint.sh"]
