import { formatCurrency } from "@stuffhub/domain";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useInventory } from "../../inventory-context";
import { LoadingImage } from "../../components/loading-image";

const titles: Record<string, string> = { rooms: "Rooms", containers: "Containers", warranties: "Warranties", maintenance: "Maintenance", receipts: "Receipts" };

export default function CollectionScreen() {
  const { kind = "rooms" } = useLocalSearchParams<{ kind: string }>();
  const { rooms, containers, receipts, warranties, maintenanceReminders, findItem } = useInventory();
  const title = titles[kind] ?? "Inventory";
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={12}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>{title}</Text><View style={styles.spacer} /></View>
    <Text style={styles.eyebrow}>MY HOME</Text><Text style={styles.title}>{title}</Text>
    {kind === "rooms" ? <><Pressable style={styles.primary} onPress={() => router.push("/add-room")}><Text style={styles.primaryText}>＋ Add room</Text></Pressable>{rooms.map((room) => <Pressable style={styles.row} key={room.id} onPress={() => router.push({ pathname: "/room/[id]", params: { id: room.id } })}><View><Text style={styles.rowTitle}>{room.name}</Text><Text style={styles.meta}>{room.items.length} items · {room.photos.length} photos</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</> : null}
    {kind === "containers" ? <><Pressable style={styles.primary} onPress={() => router.push("/add-container")}><Text style={styles.primaryText}>＋ Add container</Text></Pressable>{containers.length ? containers.map((container) => <Pressable style={styles.row} key={container.id} onPress={() => router.push({ pathname: "/container/[id]", params: { id: container.id } })}><View><Text style={styles.rowTitle}>{container.name}</Text><Text style={styles.meta}>{rooms.find((room) => room.id === container.roomId)?.name ?? "Unknown room"} · {container.itemIds.length} items</Text></View><Text style={styles.chevron}>›</Text></Pressable>) : <Empty copy="Add bins, boxes, cabinets, closets, or other item containers." />}</> : null}
    {kind === "receipts" ? receipts.length ? receipts.map((receipt) => { const item = findItem(receipt.itemIds[0] ?? ""); return <Pressable style={styles.row} key={receipt.id} onPress={() => router.push({ pathname: "/edit-receipt", params: { receiptId: receipt.id, returnTo: "receipts" } })}>{receipt.imageUri ? <LoadingImage uri={receipt.imageUri} style={styles.receiptPhoto} resizeMode="cover" /> : <View style={styles.receiptPlaceholder}><Text style={styles.receiptPlaceholderText}>▤</Text></View>}<View style={styles.receiptCopy}><Text style={styles.rowTitle}>{receipt.merchant}</Text><Text style={styles.meta}>{item?.name ?? "Unlinked item"} · {receipt.purchaseDate ?? "No date"}</Text></View><View style={styles.receiptEnd}><Text style={styles.value}>{formatCurrency(receipt.totalCents)}</Text><Text style={styles.receiptOpen}>View details  ›</Text></View></Pressable>; }) : <Empty copy="Receipts attached to items will appear here." /> : null}
    {kind === "warranties" ? <><Pressable style={styles.primary} onPress={() => router.push({ pathname: "/add-record", params: { kind: "warranty" } })}><Text style={styles.primaryText}>＋ Add warranty</Text></Pressable>{warranties.length ? warranties.map((warranty) => <Pressable style={styles.row} key={warranty.id} onPress={() => router.push({ pathname: "/add-record", params: { kind: "warranty", warrantyId: warranty.id } })}><View><Text style={styles.rowTitle}>{warranty.provider}</Text><Text style={styles.meta}>{warranty.durationMonths} months · {warranty.itemIds.length} attached items</Text></View><Text style={styles.chevron}>›</Text></Pressable>) : <Empty copy="Warranty records will appear here." />}</> : null}
    {kind === "maintenance" ? <Empty copy="Maintenance reminders and service history will appear here." /> : null}
  </ScrollView></SafeAreaView>;
}

function Empty({ copy }: { copy: string }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>Nothing here yet</Text><Text style={styles.meta}>{copy}</Text></View>; }

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: "#f4f1e9" }, content: { padding: 24, paddingBottom: 60 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 42 }, back: { color: "#17211b", fontSize: 42, lineHeight: 42 }, headerTitle: { color: "#17211b", fontWeight: "800", fontSize: 14 }, spacer: { width: 24 }, eyebrow: { color: "#234d3b", fontSize: 10, fontWeight: "800", letterSpacing: 1.5, marginBottom: 8 }, title: { color: "#17211b", fontFamily: "Georgia", fontSize: 43, marginBottom: 25 }, primary: { height: 50, marginBottom: 20, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#234d3b" }, primaryText: { color: "white", fontWeight: "800" }, row: { minHeight: 76, padding: 15, marginBottom: 9, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, borderWidth: 1, borderColor: "#dedbd1", borderRadius: 13, backgroundColor: "#fffdf8" }, rowTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 17, marginBottom: 5 }, meta: { color: "#657069", fontSize: 11, lineHeight: 17 }, value: { color: "#17211b", fontFamily: "Georgia", fontSize: 15 }, chevron: { color: "#879089", fontSize: 24 }, receiptPhoto: { width: 54, height: 62, borderRadius: 9, backgroundColor: "#e8e5dd" }, receiptPlaceholder: { width: 54, height: 62, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: "#ece9e1" }, receiptPlaceholderText: { color: "#234d3b", fontSize: 23 }, receiptCopy: { flex: 1 }, receiptEnd: { alignItems: "flex-end" }, receiptOpen: { marginTop: 5, color: "#718078", fontSize: 7.5 }, empty: { padding: 34, alignItems: "center", borderWidth: 1, borderStyle: "dashed", borderColor: "#b9b7af", borderRadius: 14 }, emptyTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 20, marginBottom: 8 } });
