import * as ImagePicker from "expo-image-picker";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { DateField } from "../components/form-fields";
import { useInventory } from "../inventory-context";
import { TappablePhoto } from "../components/tappable-photo";

type Kind = "appliance" | "warranty" | "maintenance";
const frequencyOptions = [{ id: "one_time", label: "One time" }, { id: "monthly", label: "Monthly" }, { id: "quarterly", label: "Quarterly" }, { id: "semiannual", label: "Every 6 months" }, { id: "annual", label: "Annual" }] as const;

export default function AddRecordScreen() {
  const { kind = "appliance", warrantyId = "" } = useLocalSearchParams<{ kind: Kind; warrantyId?: string }>();
  const { rooms, receipts, warranties, addItem, addWarranty, updateWarranty, addMaintenanceReminder } = useInventory();
  const existingWarranty = warranties.find((warranty) => warranty.id === warrantyId);
  const items = rooms.flatMap((room) => room.items);
  const [title, setTitle] = useState(existingWarranty?.provider ?? ""); const [description, setDescription] = useState(existingWarranty?.description ?? ""); const [date, setDate] = useState(existingWarranty?.purchaseDate ?? "");
  const [roomId, setRoomId] = useState(rooms[0]?.id ?? ""); const [itemIds, setItemIds] = useState<string[]>(existingWarranty?.itemIds ?? []); const [photos, setPhotos] = useState<string[]>(existingWarranty?.documentUris ?? []);
  const [model, setModel] = useState(""); const [serial, setSerial] = useState("");
  const [provider, setProvider] = useState(existingWarranty?.provider ?? ""); const [policy, setPolicy] = useState(existingWarranty?.policyNumber ?? ""); const [duration, setDuration] = useState(existingWarranty?.durationMonths.toString() ?? ""); const [claimContact, setClaimContact] = useState(existingWarranty?.claimContact ?? ""); const [receiptId, setReceiptId] = useState<string | null>(existingWarranty?.receiptId ?? null);
  const [frequency, setFrequency] = useState<(typeof frequencyOptions)[number]["id"]>("annual");
  const heading = kind === "appliance" ? "Add an appliance" : kind === "warranty" ? existingWarranty ? "Edit warranty" : "Add a warranty" : "Schedule maintenance";
  async function addPhotos() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsMultipleSelection: true, quality: 1 }); if (!result.canceled) setPhotos((current) => [...current, ...result.assets.map((asset) => asset.uri)]); }
  function toggleItem(id: string) { setItemIds((current) => current.includes(id) ? current.filter((entry) => entry !== id) : [...current, id]); }
  function save() {
    if (!title.trim()) return;
    if (kind === "appliance") { if (!roomId) return; addItem(roomId, { name: title, category: "Appliances", description, estimatedReplacementValueCents: 0, purchaseYear: null, serialNumber: serial.trim() || null, modelNumber: model.trim() || null, photoUris: photos }); }
    if (kind === "warranty") { const input = { provider: provider.trim() || title.trim(), policyNumber: policy.trim(), purchaseDate: date || null, durationMonths: Math.max(0, Number(duration) || 0), description, claimContact, itemIds, receiptId, documentUris: photos }; if (existingWarranty) updateWarranty(existingWarranty.id, input); else addWarranty(input); }
    if (kind === "maintenance") addMaintenanceReminder({ title: title.trim(), description, startDate: date, frequency, itemIds });
    router.back();
  }
  return <SafeAreaView style={styles.safeArea}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>{heading}</Text><View style={styles.spacer} /></View><Text style={styles.eyebrow}>MY HOME</Text><Text style={styles.title}>{heading}.</Text>
    <Label text={kind === "warranty" ? "WARRANTY NAME *" : kind === "maintenance" ? "REMINDER NAME *" : "APPLIANCE NAME *"}><TextInput style={styles.input} value={title} onChangeText={setTitle} /></Label>
    {kind === "appliance" ? <><Label text="ROOM"><Choices values={rooms.map((room) => ({ id: room.id, label: room.name }))} selected={[roomId]} onPress={(id) => setRoomId(id)} /></Label><Label text="MODEL NUMBER"><TextInput style={styles.input} value={model} onChangeText={setModel} /></Label><Label text="SERIAL NUMBER"><TextInput style={styles.input} value={serial} onChangeText={setSerial} /></Label></> : null}
    {kind === "warranty" ? <><Label text="PROVIDER"><TextInput style={styles.input} value={provider} onChangeText={setProvider} /></Label><Label text="POLICY / CONTRACT NUMBER"><TextInput style={styles.input} value={policy} onChangeText={setPolicy} /></Label><Label text="PURCHASE DATE"><DateField value={date} onChangeText={setDate} /></Label><Label text="DURATION IN MONTHS"><TextInput style={styles.input} value={duration} onChangeText={(value) => setDuration(value.replace(/\D/g, ""))} keyboardType="number-pad" /></Label><Label text="CLAIM CONTACT / WEBSITE"><TextInput style={styles.input} value={claimContact} onChangeText={setClaimContact} /></Label><Label text="ATTACH RECEIPT"><Choices values={receipts.map((receipt) => ({ id: receipt.id, label: receipt.merchant }))} selected={receiptId ? [receiptId] : []} onPress={(id) => setReceiptId(receiptId === id ? null : id)} /><Pressable onPress={() => router.push("/add-receipt")}><Text style={styles.link}>＋ Create a receipt</Text></Pressable></Label></> : null}
    {kind === "maintenance" ? <><Label text="START DATE"><DateField value={date} onChangeText={setDate} /></Label><Label text="FREQUENCY"><Choices values={[...frequencyOptions]} selected={[frequency]} onPress={(id) => setFrequency(id as typeof frequency)} /></Label></> : null}
    {kind !== "appliance" ? <Label text="ATTACH ITEMS OR APPLIANCES"><Choices values={items.map((item) => ({ id: item.id, label: item.name }))} selected={itemIds} onPress={toggleItem} /></Label> : null}
    <Label text="DESCRIPTION / CLAIM NOTES"><TextInput style={[styles.input, styles.textArea]} value={description} onChangeText={setDescription} multiline textAlignVertical="top" /></Label>
    {kind !== "maintenance" ? <><Pressable style={styles.photoButton} onPress={addPhotos}><Text style={styles.photoButtonText}>＋ Attach photos or documents</Text></Pressable>{photos.length ? <ScrollView horizontal contentContainerStyle={styles.photos}>{photos.map((uri, index) => <TappablePhoto key={uri} uri={uri} title={`${title || "Document"}, image ${index + 1}`} style={styles.photo} />)}</ScrollView> : null}</> : null}
    <Pressable disabled={!title.trim()} style={[styles.save, !title.trim() && styles.disabled]} onPress={save}><Text style={styles.saveText}>Save {kind}</Text></Pressable>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <View style={styles.field}><Text style={styles.label}>{text}</Text>{children}</View>; }
function Choices({ values, selected, onPress }: { values: ReadonlyArray<{ id: string; label: string }>; selected: string[]; onPress: (id: string) => void }) { return values.length ? <View style={styles.choices}>{values.map((value) => <Pressable key={value.id} style={[styles.choice, selected.includes(value.id) && styles.choiceSelected]} onPress={() => onPress(value.id)}><Text style={[styles.choiceText, selected.includes(value.id) && styles.choiceTextSelected]}>{value.label}</Text></Pressable>)}</View> : <Text style={styles.emptyText}>No records available yet.</Text>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, safeArea: { flex: 1, backgroundColor: "#f4f1e9" }, content: { padding: 24, paddingBottom: 60 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 40 }, back: { color: "#17211b", fontSize: 42 }, headerTitle: { color: "#17211b", fontWeight: "800" }, spacer: { width: 24 }, eyebrow: { color: "#234d3b", fontSize: 10, fontWeight: "800", letterSpacing: 1.5 }, title: { color: "#17211b", fontFamily: "Georgia", fontSize: 40, marginTop: 8, marginBottom: 28 }, field: { marginBottom: 22 }, label: { color: "#657069", fontSize: 9, fontWeight: "800", letterSpacing: 1.2, marginBottom: 8 }, input: { height: 52, paddingHorizontal: 14, borderWidth: 1, borderColor: "#d2d0c8", borderRadius: 11, color: "#17211b", backgroundColor: "#fffdf8" }, textArea: { height: 110, paddingTop: 14 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: "#d2d0c8", borderRadius: 18, backgroundColor: "#fffdf8" }, choiceSelected: { borderColor: "#234d3b", backgroundColor: "#dce9df" }, choiceText: { color: "#657069", fontSize: 11, fontWeight: "700" }, choiceTextSelected: { color: "#234d3b" }, link: { marginTop: 12, color: "#234d3b", fontWeight: "800", fontSize: 12 }, emptyText: { color: "#657069", fontSize: 11 }, photoButton: { height: 50, marginBottom: 14, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#234d3b", borderRadius: 11 }, photoButtonText: { color: "#234d3b", fontWeight: "800" }, photos: { gap: 9, marginBottom: 20 }, photo: { width: 90, height: 70, borderRadius: 9 }, save: { height: 53, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#234d3b" }, saveText: { color: "white", fontWeight: "800" }, disabled: { opacity: .35 } });
