import { formatCurrency } from "@stuffhub/domain";
import { router } from "expo-router";
import type { ComponentType } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View, type ImageSourcePropType } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import Svg, { Defs, LinearGradient, Rect, Stop } from "react-native-svg";
import { Box, Camera, Check, ChevronRight, Clock3, Home, Plus, QrCode, ReceiptText, Search, Sparkles, TrendingUp, UserRound, type LucideProps } from "lucide-react-native";
import { useInventory } from "../inventory-context";
import { LoadingImage } from "../components/loading-image";

type Collection = "rooms" | "containers" | "warranties" | "maintenance" | "receipts";
function dayGreeting() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }

export default function HomeScreen() {
  const { rooms, containers, receipts, maintenanceReminders } = useInventory();
  const items = rooms.flatMap((room) => room.items);
  const total = items.reduce((sum, item) => sum + item.estimatedReplacementValueCents, 0);
  const recent = [...items].reverse().slice(0, 4);
  const greeting = dayGreeting();
  const activeDays = Math.min(7, items.length);
  const weekDays = ["M", "T", "W", "T", "F", "S", "S"];
  const open = (kind: Collection) => router.push({ pathname: "/collection/[kind]", params: { kind } });

  return <SafeAreaView style={styles.safeArea} edges={["top"]}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.brandRow}><View style={styles.brandIdentity}><View style={styles.mark}><Text style={styles.markText}>S</Text></View><Text style={styles.brand}>StuffHub</Text></View><Pressable style={styles.scanner} onPress={() => router.push("/scan-container")} accessibilityLabel="Scan container QR code"><QrCode size={21} color="#24533e" /></Pressable></View>

      <View style={styles.hero}>
        <Image source={require("../../assets/hero.png")} style={styles.heroImage} resizeMode="cover" />
        <Svg style={styles.heroGradient} width="100%" height="100%" pointerEvents="none">
          <Defs><LinearGradient id="heroFade" x1="0%" y1="0%" x2="100%" y2="0%"><Stop offset="0" stopColor="#f6f3ec" stopOpacity="1" /><Stop offset="0.48" stopColor="#f6f3ec" stopOpacity="1" /><Stop offset="0.62" stopColor="#f6f3ec" stopOpacity="0.94" /><Stop offset="0.76" stopColor="#f6f3ec" stopOpacity="0.4" /><Stop offset="0.91" stopColor="#f6f3ec" stopOpacity="0" /></LinearGradient></Defs>
          <Rect x="0" y="0" width="100%" height="100%" fill="url(#heroFade)" />
        </Svg>
        <View style={styles.heroCopy}><Text style={styles.eyebrow}>WELCOME HOME</Text><Text style={styles.title}>Good{`\n`}{greeting}.</Text><Text style={styles.intro}>Here’s your home,{`\n`}organized and protected.</Text></View>
      </View>

      <View style={styles.snapshotCard}><Text style={styles.cardKicker}>YOUR HOME SNAPSHOT</Text><View style={styles.snapshotGrid}>
        <Snapshot icon={Check} value={items.length} label="Items" note="documented" />
        <Snapshot icon={Box} value={containers.length} label="Containers" note="tracked" />
        <Snapshot icon={ReceiptText} value={receipts.length} label="Receipts" note="saved" />
        <Snapshot icon={Clock3} value={maintenanceReminders.length} label="Maintenance" note="scheduled" />
      </View></View>

      <Pressable style={({ pressed }) => [styles.captureBanner, pressed && styles.pressed]} onPress={() => router.push("/add-item")}>
        <View style={styles.captureIcon}><Camera size={25} color="white" /></View><Sparkles size={17} color="#e4f4a9" style={styles.sparkle} />
        <View style={styles.captureCopy}><Text style={styles.captureTitle}>Add an item</Text><Text style={styles.captureNote}>Document what matters.{`\n`}Build your home record.</Text></View>
        <View style={styles.getStarted}><Text style={styles.getStartedText}>Get started</Text><ChevronRight size={15} color="#24533e" /></View>
      </Pressable>

      <View style={styles.insightRow}>
        <View style={styles.valueCard}><Text style={styles.cardKicker}>ESTIMATED REPLACEMENT VALUE</Text><Text style={styles.totalValue}>{formatCurrency(total)}</Text><View style={styles.trendPill}><TrendingUp size={11} color="#24533e" /><Text style={styles.trendText}>Documented total</Text></View><Text style={styles.valueMeta}>{rooms.length} rooms · {items.length} documented items</Text><View style={styles.chartLine}><View style={styles.chartDot} /></View></View>
        <View style={styles.streakCard}><Text style={styles.cardKicker}>THIS WEEK</Text><View style={styles.streakSummary}><Image source={require("../../assets/badge1.png")} style={styles.badgeImage} resizeMode="contain" /><View style={styles.streakCopy}><Text style={styles.streakLead}>You documented</Text><Text style={styles.streakCount}>{items.length} {items.length === 1 ? "item" : "items"}</Text><Text style={styles.streakNote}>{items.length ? "Keep it up!" : "Let’s get started!"}</Text></View></View><View style={styles.weekRow}>{weekDays.map((day, index) => <View style={styles.weekDay} key={`${day}-${index}`}><View style={[styles.dayDot, index < activeDays && styles.dayDotActive]}>{index < activeDays ? <Check size={8} color="white" /> : null}</View><Text style={[styles.dayLabel, index < activeDays && styles.dayLabelActive]}>{day}</Text></View>)}</View></View>
      </View>

      <View style={styles.sectionHeader}><View><Text style={styles.eyebrow}>RECENTLY DOCUMENTED</Text><Text style={styles.sectionTitle}>Your latest records</Text></View><Pressable onPress={() => open("rooms")}><Text style={styles.viewAll}>View all</Text></Pressable></View>
      {recent.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.recentRow}>{recent.map((item) => <Pressable style={({ pressed }) => [styles.recentCard, pressed && styles.pressed]} key={item.id} onPress={() => router.push({ pathname: "/item/[id]", params: { id: item.id } })}>{item.photoUris?.[0] ? <LoadingImage uri={item.photoUris[0]} style={styles.recentImage} /> : <View style={styles.recentPlaceholder}><Box size={25} color="#24533e" /></View>}<Text style={styles.recentTitle} numberOfLines={1}>{item.name}</Text><Text style={styles.recentMeta} numberOfLines={1}>{rooms.find((room) => room.id === item.roomId)?.name ?? item.category}</Text></Pressable>)}</ScrollView> : <Pressable style={styles.emptyRecent} onPress={() => router.push("/select-room")}><Camera size={21} color="#24533e" /><View><Text style={styles.emptyTitle}>Your first records will appear here</Text><Text style={styles.emptyNote}>Photograph a room to get started.</Text></View></Pressable>}

      <View style={styles.sectionHeader}><View><Text style={styles.eyebrow}>EXPLORE YOUR HOME</Text><Text style={styles.sectionTitle}>Everything in its place</Text></View></View>
      <View style={styles.exploreGrid}><Explore title="Rooms" detail={`${rooms.length} spaces documented`} image={require("../../assets/room.png")} kind="room" progress={Math.min(100, rooms.length * 20)} onPress={() => open("rooms")} /><Explore title="Containers" detail={`${containers.length} containers`} image={require("../../assets/tote.png")} kind="tote" onPress={() => open("containers")} /><Explore title="Protection" detail="Warranties & coverage" image={require("../../assets/protection_badge.png")} kind="badge" onPress={() => open("warranties")} /><Explore title="History" detail="Maintenance timeline" image={require("../../assets/calendar.png")} kind="badge" onPress={() => open("maintenance")} /><Explore title="Receipts" detail="Proof of purchase" image={require("../../assets/receipt.png")} kind="receipt" onPress={() => open("receipts")} /></View>
    </ScrollView>

    <View style={styles.bottomNav}><NavItem icon={Home} label="Home" active onPress={() => {}} /><NavItem icon={QrCode} label="Scan" onPress={() => router.push("/scan-container")} /><Pressable style={styles.addButton} onPress={() => router.push("/add-item")} accessibilityLabel="Add item"><Plus size={25} color="white" /></Pressable><NavItem icon={Search} label="Search" onPress={() => router.push("/search")} /><NavItem icon={UserRound} label="Profile" onPress={() => open("receipts")} /></View>
  </SafeAreaView>;
}

function Snapshot({ icon: Icon, value, label, note }: { icon: ComponentType<LucideProps>; value: number | string; label: string; note: string }) { return <View style={styles.snapshotStat}><View style={styles.statIcon}><Icon size={15} color="#24533e" /></View><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text><Text style={styles.statNote}>{note}</Text></View>; }
function Explore({ title, detail, image, kind, progress, onPress }: { title: string; detail: string; image: ImageSourcePropType; kind: "room" | "tote" | "badge" | "receipt"; progress?: number; onPress: () => void }) { return <Pressable style={({ pressed }) => [styles.exploreCard, kind === "room" && styles.roomCard, pressed && styles.pressed]} onPress={onPress}><Image source={image} resizeMode={kind === "room" ? "cover" : "contain"} style={[styles.exploreArtwork, kind === "room" && styles.roomArtwork, kind === "tote" && styles.toteArtwork, kind === "badge" && styles.badgeArtwork, kind === "receipt" && styles.receiptArtwork]} />{kind === "room" ? <Svg style={styles.exploreFade} pointerEvents="none"><Defs><LinearGradient id="roomCardFade" x1="0%" y1="0%" x2="100%" y2="0%"><Stop offset="0" stopColor="#fffdf8" stopOpacity="1" /><Stop offset="0.36" stopColor="#fffdf8" stopOpacity="1" /><Stop offset="0.49" stopColor="#fffdf8" stopOpacity="0.82" /><Stop offset="0.66" stopColor="#fffdf8" stopOpacity="0.34" /><Stop offset="0.82" stopColor="#fffdf8" stopOpacity="0" /></LinearGradient></Defs><Rect x="0" y="0" width="100%" height="100%" fill="url(#roomCardFade)" /></Svg> : null}<View style={[styles.exploreCopy, kind === "room" && styles.roomCopy]}><Text style={styles.exploreTitle}>{title}</Text><Text style={styles.exploreDetail}>{detail}</Text>{progress !== undefined ? <View style={[styles.exploreProgress, kind === "room" && styles.roomProgress]}><View style={[styles.exploreProgressFill, { width: `${progress}%` }]} /></View> : null}</View><View style={styles.exploreArrow}><ChevronRight size={17} color="#24533e" /></View></Pressable>; }
function NavItem({ icon: Icon, label, active, onPress }: { icon: ComponentType<LucideProps>; label: string; active?: boolean; onPress: () => void }) { return <Pressable style={styles.navItem} onPress={onPress}><Icon size={20} color={active ? "#24533e" : "#89908b"} fill={active ? "#dce9df" : "transparent"} /><Text style={[styles.navLabel, active && styles.navLabelActive]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f6f3ec" }, content: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 116 },
  brandRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 31 }, brandIdentity: { flexDirection: "row", alignItems: "center", gap: 9 }, mark: { width: 31, height: 31, borderRadius: 8, backgroundColor: "#24533e", alignItems: "center", justifyContent: "center" }, markText: { color: "white", fontWeight: "800", fontSize: 12 }, brand: { color: "#17211b", fontFamily: "Georgia", fontWeight: "700", fontSize: 22 }, scanner: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#dedbd1", borderRadius: 11, backgroundColor: "#fffdf8" },
  hero: { height: 252, marginHorizontal: -20, marginTop: -8, marginBottom: 20, overflow: "hidden" }, heroImage: { position: "absolute", top: 0, right: 0, width: "82%", height: "100%" }, heroGradient: { position: "absolute", zIndex: 2, top: 0, right: 0, bottom: 0, left: 0 }, heroCopy: { position: "absolute", left: 20, top: 42, zIndex: 5 }, eyebrow: { color: "#24533e", fontWeight: "800", fontSize: 10, letterSpacing: 1.35, marginBottom: 7 }, title: { color: "#17211b", fontFamily: "Georgia", fontSize: 40, lineHeight: 42, letterSpacing: -1.2 }, intro: { color: "#657069", fontSize: 13, lineHeight: 19, marginTop: 11 },
  snapshotCard: { padding: 16, borderWidth: 1, borderColor: "#dedbd1", borderRadius: 16, backgroundColor: "#fffdf8", shadowColor: "#183b2b", shadowOpacity: .04, shadowRadius: 12, shadowOffset: { width: 0, height: 5 } }, cardKicker: { color: "#68736c", fontSize: 9, fontWeight: "800", letterSpacing: .8, marginBottom: 13 }, snapshotGrid: { flexDirection: "row" }, snapshotStat: { flex: 1 }, statIcon: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: "#e2ede2", marginBottom: 8 }, statValue: { color: "#17211b", fontFamily: "Georgia", fontSize: 25, lineHeight: 27 }, statLabel: { color: "#17211b", fontSize: 10, fontWeight: "700", marginTop: 3 }, statNote: { color: "#6d7770", fontSize: 8.5, lineHeight: 11, marginTop: 3 },
  captureBanner: { minHeight: 108, marginVertical: 13, padding: 17, flexDirection: "row", alignItems: "center", borderRadius: 16, backgroundColor: "#1e543c", overflow: "hidden" }, captureIcon: { width: 50, height: 50, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#ffffff3d", borderRadius: 25, backgroundColor: "#ffffff0d" }, sparkle: { position: "absolute", left: 56, top: 13 }, captureCopy: { marginLeft: 14, flex: 1 }, captureTitle: { color: "white", fontFamily: "Georgia", fontSize: 17, lineHeight: 20 }, captureNote: { color: "#d5e3d9", fontSize: 10, lineHeight: 14, marginTop: 7 }, getStarted: { height: 42, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 3, borderRadius: 10, backgroundColor: "#eef2dd" }, getStartedText: { color: "#24533e", fontSize: 10, fontWeight: "800" }, pressed: { opacity: .78, transform: [{ scale: .99 }] },
  insightRow: { flexDirection: "row", gap: 10 }, valueCard: { flex: 1.08, height: 194, padding: 15, borderWidth: 1, borderColor: "#e5dfc2", borderRadius: 15, backgroundColor: "#fff9df", overflow: "hidden" }, totalValue: { fontFamily: "Georgia", color: "#17211b", fontSize: 28, lineHeight: 32 }, trendPill: { alignSelf: "flex-start", marginTop: 10, paddingVertical: 5, paddingHorizontal: 8, flexDirection: "row", gap: 4, alignItems: "center", borderRadius: 20, backgroundColor: "#e6efcf" }, trendText: { color: "#24533e", fontSize: 8.5, fontWeight: "700" }, valueMeta: { color: "#657069", fontSize: 8.5, lineHeight: 12, marginTop: 24 }, chartLine: { position: "absolute", right: -8, bottom: 19, width: 80, height: 2, backgroundColor: "#79aa79", transform: [{ rotate: "-12deg" }] }, chartDot: { position: "absolute", right: 0, top: -2, width: 6, height: 6, borderRadius: 3, backgroundColor: "#79aa79" }, streakCard: { flex: .92, height: 194, padding: 13, borderWidth: 1, borderColor: "#dedbd1", borderRadius: 15, backgroundColor: "#fffdf8" }, streakSummary: { flexDirection: "row", alignItems: "center", marginTop: 1 }, badgeImage: { width: 58, height: 52 }, streakCopy: { flex: 1, marginLeft: 3 }, streakLead: { color: "#657069", fontSize: 8.5 }, streakCount: { color: "#17211b", fontFamily: "Georgia", fontSize: 17, marginVertical: 3 }, streakNote: { color: "#657069", fontSize: 8.5 }, weekRow: { marginTop: 20, flexDirection: "row", justifyContent: "space-between" }, weekDay: { alignItems: "center", gap: 6 }, dayDot: { width: 18, height: 18, alignItems: "center", justifyContent: "center", borderWidth: 1.5, borderColor: "#d2d3cc", borderRadius: 9, backgroundColor: "#fffdf8" }, dayDotActive: { borderColor: "#24533e", backgroundColor: "#24533e" }, dayLabel: { color: "#777f79", fontSize: 8 }, dayLabelActive: { color: "#17211b", fontWeight: "800" },
  sectionHeader: { marginTop: 31, marginBottom: 11, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" }, sectionTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 23 }, viewAll: { color: "#24533e", fontSize: 11, fontWeight: "700" }, recentRow: { gap: 10, paddingRight: 4 }, recentCard: { width: 112 }, recentImage: { width: 112, height: 77, borderRadius: 11 }, recentPlaceholder: { width: 112, height: 77, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: "#e7e5dc" }, checkBadge: { position: "absolute", top: 6, right: 6, width: 18, height: 18, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "white", borderRadius: 9, backgroundColor: "#4d9c48" }, recentTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 13, marginTop: 7 }, recentMeta: { color: "#6f7972", fontSize: 10, marginTop: 3 }, emptyRecent: { minHeight: 76, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderStyle: "dashed", borderColor: "#b9b7af", borderRadius: 14 }, emptyTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 14 }, emptyNote: { color: "#657069", fontSize: 11, marginTop: 3 },
  exploreGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, exploreCard: { position: "relative", width: "48.5%", height: 136, padding: 14, overflow: "hidden", borderWidth: 1, borderColor: "#dedbd1", borderRadius: 16, backgroundColor: "#fffdf8" }, roomCard: { height: 142, padding: 0 }, exploreArtwork: { position: "absolute", right: 8, bottom: 6, width: "50%", height: "57%" }, roomArtwork: { top: 0, right: 0, bottom: 0, width: "66%", height: "100%", opacity: .88 }, toteArtwork: { right: 5, bottom: 5, width: "57%", height: "58%" }, badgeArtwork: { right: 12, bottom: 5, width: "47%", height: "53%" }, receiptArtwork: { right: 20, bottom: -10, width: "34%", height: "65%" }, exploreFade: { position: "absolute", zIndex: 1, top: 0, right: 0, bottom: 0, left: 0, width: "100%", height: "100%" }, exploreCopy: { position: "relative", zIndex: 2, width: "68%", height: "100%" }, roomCopy: { padding: 14 }, exploreTitle: { color: "#17211b", fontFamily: "Georgia", fontSize: 17 }, exploreDetail: { color: "#657069", fontSize: 10, lineHeight: 13, marginTop: 5 }, exploreArrow: { position: "absolute", zIndex: 3, top: 10, right: 10, width: 31, height: 31, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#dedbd1", borderRadius: 16, backgroundColor: "#fffdf8f2" }, exploreProgress: { position: "absolute", left: 0, right: 0, bottom: 2, height: 5, overflow: "hidden", borderRadius: 3, backgroundColor: "#e4e6df" }, roomProgress: { right: -18, bottom: 16, left: 14 }, exploreProgressFill: { height: "100%", minWidth: 16, borderRadius: 3, backgroundColor: "#24533e" },
  bottomNav: { position: "absolute", left: 14, right: 14, bottom: 12, height: 70, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-around", borderWidth: 1, borderColor: "#dedbd1", borderRadius: 24, backgroundColor: "#fffdf8", shadowColor: "#17211b", shadowOpacity: .12, shadowRadius: 18, shadowOffset: { width: 0, height: 7 } }, navItem: { width: 52, alignItems: "center", justifyContent: "center", gap: 4 }, navLabel: { color: "#747d77", fontSize: 9 }, navLabelActive: { color: "#24533e", fontWeight: "800" }, addButton: { width: 47, height: 47, alignItems: "center", justifyContent: "center", borderRadius: 24, backgroundColor: "#24533e", shadowColor: "#24533e", shadowOpacity: .2, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
});
